enum eErrorCodes {
  DEFAULT = 'DEFAULT_ERROR',
  GET_POKEMON = 'GET_POKEMON_FAILED',
  GET_ALL_FAVORITES_POKEMON = 'GET_ALL_FAVORITES_POKEMON_FAILED',
  GET_POKEDEX_INFO = 'GET_POKEDEX_INFO_FAILED',
}

export default eErrorCodes;
