enum ErrorNames {
  FAULT_ADAPTER = 'FAULT_ADAPTER_ERROR',
  FAULT_INFRA = 'FAULT_INFRA_ERROR',
  FAULT_DOMAIN = 'FAULT_DOMAIN_ERROR',
  FAULT_CONTROLLER = 'FAULT_CONTROLLER_ERROR',
}

export default ErrorNames;
